---
title: "RANDOM FOREST FIT"
author: "Victor M. Uribe"
date: "2023-01-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tidymodels)
library(finetune)
```



```{r}
members <- data.table::fread('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/members.csv')

everest <- members %>% # should have an age
  filter(age != 'NA' & peak_name == "Everest" & expedition_role == "Climber") %>% 
  select(-c(peak_id,peak_name,expedition_id, member_id, expedition_role, death_height_metres,
            injury_height_metres, highpoint_metres, death_cause, injury_type, hired, solo)) %>%
  mutate(
    #death_height_metres = ifelse(death_height_metres == NA, 0, death_height_metres), # issue wiith levels for some reason
    #injury_height_metres = ifelse(injury_height_metres == NA, 0, injury_height_metres), # gives leveling issue 
    #highpoint_metres = ifelse(highpoint_metres == 'NA', 0, highpoint_metres), # thows off the p values
    season = factor(season),
    sex = factor(sex),
    citizenship = factor(citizenship), # not significant after testing
    #expedition_role = factor(expedition_role), # not significant after testing
    #hired = factor(hired), 
    success = factor(success), # value being predicted
    #solo = factor(solo),
    oxygen_used = factor(oxygen_used),
    died = factor(died),
    #death_cause = factor(death_cause), # issue
    injured = factor(injured)#,
    #injury_type = factor(injury_type) # issue with levels
  ) 
```


```{r}
everest$success %>% table()
```

```{r}
## Original Data Split
set.seed(123)

everest_split <- initial_split(everest, prop = .7)
everest_train <- training(everest_split)
everest_test <- testing(everest_split)

everest_fold <- vfold_cv(everest_train, strata = success)
```


```{r}
ran_spec <- rand_forest(
  mtry = tune(),
  min_n = tune(),
  trees = tune()
) %>% 
  set_engine("ranger", importance = "impurity") %>% 
  set_mode("classification")

ran_rec <- recipe(success~., everest_train) %>%
  themis::step_rose(success) %>% 
  step_other(citizenship, threshold = .05) %>% 
  step_dummy(all_nominal_predictors())

ran_wf <- workflow() %>% 
  add_model(ran_spec) %>% 
  add_recipe(ran_rec)
```


```{r}
doParallel::registerDoParallel()
set.seed(123)

ran_para <- parameters(
  finalize(mtry(), everest_train),
  min_n(),
  trees()
)

ran_grid <- grid_max_entropy(
  ran_para,
  size = 20
)

ran_tune <- tune_race_anova(
  ran_wf,
  resamples = everest_fold,
  grid = ran_grid,
  metrics = metric_set(roc_auc),
  control = control_race(verbose_elim = TRUE)
)
```


```{r}
#ran_tune %>% autoplot()
```


```{r}
doParallel::registerDoParallel()
best_run <- ran_tune %>% 
  select_best("roc_auc")

fin_ran_wf <- finalize_workflow(
  ran_wf,
  best_run
)

fit_ran <- fin_ran_wf %>% 
  fit(everest_train)
```





```{r}
doParallel::registerDoParallel()

ran_pred <- fit_ran %>% 
  predict(new_data = everest_test) 

ran_tmp <- factor(ifelse(ran_pred == TRUE, TRUE, FALSE)) 
caret::confusionMatrix(ran_tmp, everest_test[["success"]])
```


```{r}
#v1 <- 
fit_ran %>% extract_fit_parsnip() %>% 
  vip::vip(aesthetic = list(fill = "orange")) + theme_gray(base_size = 15) + 
  ggtitle("Logistic with assumptions met")
  
```


### Threshhold = 0 and step_rose
Accuracy : 0.8491
Sensitivity : 0.7876          
Specificity : 0.9591


### Threshhold = 0
Accuracy : 0.8669 
Sensitivity : 0.8476          
Specificity : 0.9014


### Threshhold = .005
Accuracy : 0.858
Sensitivity : 0.8273        
Specificity : 0.9130 


### Threshhold = .05
Accuracy : 0.8545 
Sensitivity : 0.8189          
Specificity : 0.9183






